### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by imeDevelopers** [Muljin/msal-flutter#15]
```
E/AndroidRuntime(22031): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime(22031):        at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfigurationInternal(PublicClientApplicationConfigurationFactory.java:96)
E/AndroidRuntime(22031):        at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:70)
E/AndroidRuntime(22031):        at com.microsoft.identity.client.PublicClientApplication$4.run(PublicClientApplication.java:459)
E/AndroidRuntime(22031):        at java.lang.Thread.run(Thread.java:919)
I/Process (22031): Sending signal. PID: 22031 SIG: 9
```

**Comment by ngocbaomobile** [comment]
did you resolve that,  I'm facing the same issue. testing on android
