### ISSUE TITLE
Java null pointer exception

### ISSUE THREAD

**Issue by qaniel** [Muljin/msal-flutter#24]
Getting this error on my app startup
```
E/AndroidRuntime(11067): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime(11067): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfigurationInternal(PublicClientApplicationConfigurationFactory.java:96)
E/AndroidRuntime(11067): 	at com.microsoft.identity.client.PublicClientApplicationConfigurationFactory.initializeConfiguration(PublicClientApplicationConfigurationFactory.java:60)
E/AndroidRuntime(11067): 	at com.microsoft.identity.client.PublicClientApplication$3.run(PublicClientApplication.java:366)
E/AndroidRuntime(11067): 	at java.lang.Thread.run(Thread.java:1012)
```

I have no idea what it could be, any hint guys?

**Comment by Abhi011999** [comment]
don't trust readme file
go into `example`, check out the latest code and run from there
worked for me

**Comment by nayanaubie** [comment]
Same issue for me

**Comment by Noahbanderson** [comment]
I believe the error is thrown while trying to parse the msal_default_config.json file. I took the example's [file](https://github.com/Muljin/msal-flutter/blob/master/example/android/app/src/main/res/raw/msal_default_config.json) and merged it with what the android app registration page gave me (and when they conflicted I used the properties in the app registration page over the example's file).
